// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_ContainerPageM1;
extern lv_obj_t *ui_Chart1;
extern lv_obj_t *ui_ButtonChartRestart;
extern lv_obj_t *ui_ContainerPageReflowRun;
extern lv_obj_t *ui_ReflowRunChart;
extern lv_obj_t *ui_LabelReflowRunTempTset;
extern lv_obj_t *ui_LabelReflowRunPower;
extern lv_obj_t *ui_LabelReflowRunTime;
extern lv_obj_t *ui_LabelReflowRunState;
extern lv_obj_t *ui_LabelReflowRunHint;
extern lv_obj_t *ui_ReflowRunBottomBar;
extern lv_obj_t *ui_ButtonReflowRunSelect;
extern lv_obj_t *ui_LabelReflowRunSelect;
extern lv_obj_t *ui_ButtonReflowRunEdit;
extern lv_obj_t *ui_LabelReflowRunEdit;
extern lv_obj_t *ui_ButtonReflowRunStart;
extern lv_obj_t *ui_LabelReflowRunStart;
extern lv_obj_t *ui_ContainerPage0;
extern lv_obj_t *ui_Container1c1;
extern lv_obj_t *ui_Container1c1c1;
extern lv_obj_t *ui_LabelRealVoltage;
extern lv_obj_t *ui_Container1c1c2;
extern lv_obj_t *ui_LabelRealCurrent;
extern lv_obj_t *ui_Container1c1c3;
extern lv_obj_t *ui_LabelRealPower;
extern lv_obj_t *ui_Container1c2;
extern lv_obj_t *ui_Container1c2c1;
extern lv_obj_t *ui_LabelRealTemp;
extern lv_obj_t *ui_Container1c2c2;
extern lv_obj_t *ui_LabelRealDuty;
extern lv_obj_t *ui_Container1c2c3;
extern lv_obj_t *ui_ButtonHeatingToggle;
extern lv_obj_t *ui_LabelHeatingToggle;
extern lv_obj_t *ui_ContainerPageM2;
extern lv_obj_t *ui_Container12;
extern lv_obj_t *ui_Container7;
extern lv_obj_t *ui_LabelRealTemp1;
extern lv_obj_t *ui_LabelRealTemp4;
extern lv_obj_t *ui_LabelRealTemp2;
extern lv_obj_t *ui_Container13;
extern lv_obj_t *ui_Container19;
extern lv_obj_t *ui_LabelRealTemp3;
extern lv_obj_t *ui_Container15;
extern lv_obj_t *ui_LabelRealVoltage1;
extern lv_obj_t *ui_Container17;
extern lv_obj_t *ui_LabelRealCurrent1;
extern lv_obj_t *ui_Container18;
extern lv_obj_t *ui_LabelRealPower1;
extern lv_obj_t *ui_BarRealDuty;
extern lv_obj_t *ui_ContainerPage1;
extern lv_obj_t *ui_Container11;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_SliderSetTemp;
extern lv_obj_t *ui_LabelSetTemp;
extern lv_obj_t *ui_Container8;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_SliderSetKp;
extern lv_obj_t *ui_LabelSetKp;
extern lv_obj_t *ui_Container9;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_SliderSetKi;
extern lv_obj_t *ui_LabelSetKi;
extern lv_obj_t *ui_Container10;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_SliderSetKd;
extern lv_obj_t *ui_LabelSetKd;
extern lv_obj_t *ui_LabelDebug;
extern lv_obj_t *ui_ContainerPage2;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_SliderSetMaxPower;
extern lv_obj_t *ui_LabelSetMaxPower;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_SliderSetRPcb;
extern lv_obj_t *ui_LabelSetRPcb;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_SliderSetRDiv;
extern lv_obj_t *ui_LabelSetRDiv;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_SliderSetADCOffset;
extern lv_obj_t *ui_LabelSetADCOffset;
extern lv_obj_t *ui_ContainerPage4;
extern lv_obj_t *ui_Container20;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_SliderSetMinVolt;
extern lv_obj_t *ui_LabelSetMinVolt;
extern lv_obj_t *ui_Container21;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_SliderSetShuntR;
extern lv_obj_t *ui_LabelSetShuntR;
extern lv_obj_t *ui_Container22;
extern lv_obj_t *ui_LabelSoftStart;
extern lv_obj_t *ui_SliderSetSoftStartTime;
extern lv_obj_t *ui_LabelSetSoftStartTime;
extern lv_obj_t *ui_ContainerPage3;
extern lv_obj_t *ui_Container16;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_SliderSetBL;
extern lv_obj_t *ui_LabelSetBL;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_SliderSetVol;
extern lv_obj_t *ui_LabelSetVol;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_SliderSetNote;
extern lv_obj_t *ui_LabelSetNote;
extern lv_obj_t *ui_Container14;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_SliderSetTiltThreshold;
extern lv_obj_t *ui_LabelSetTiltThreshold;
extern lv_obj_t *ui_ContainerPage5;
extern lv_obj_t *ui_LabelPDInfo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

